import Header from '@/components/header';
import { glegoo, roboto } from '@/styles/fonts';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={`${roboto.variable} ${glegoo.variable}`}>
			<body>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	);
}
