import Header from '@/components/header';
import { glegoo } from '@/styles/fonts';
import '@/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={glegoo.className}>
			<body>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	);
}
